# $FreeBSD: src/sys/boot/i386/zfsloader/Makefile,v 1.1 2009/11/23 16:00:16 rnoland Exp $

.PATH:	${.CURDIR}/../loader

LOADER=		zfsloader
NEWVERSWHAT=	"ZFS enabled bootstrap loader" i386
LOADER_ZFS_SUPPORT=yes
LOADER_ONLY=	yes
NO_MAN=		yes

.include "${.CURDIR}/../loader/Makefile"

