/*
 * This file acts as a template for config.c that will be generated in the
 * kernel build directory after config(8) has been successfully run.
 *
 * $FreeBSD: src/usr.sbin/config/kernconf.tmpl,v 1.2 2007/05/16 16:08:04 wkoszek Exp $
 */
#include "opt_config.h"
#ifdef INCLUDE_CONFIG_FILE

/*
 * For !INCLUDE_CONFIG_FILE case, you should look at kern_mib.c. This is
 * where kernconfstring is defined then.
 */
const char kernconfstring[] __attribute__ ((section("kern_conf"))) =
"options	CONFIG_AUTOGENERATED\n\
ident	SENTRY5\n\
machine	mips\n\
cpu	CPU_MIPS4KC\n\
makeoptions	MODULES_OVERRIDE=""\n\
makeoptions	DEBUG=-g\n\
makeoptions	MIPS_LITTLE_ENDIAN=defined\n\
options	INVARIANT_SUPPORT\n\
options	INVARIANTS\n\
options	_KPOSIX_PRIORITY_SCHEDULING\n\
options	PSEUDOFS\n\
options	NFS_ROOT\n\
options	NFSCLIENT\n\
options	INET\n\
options	SCHED_4BSD\n\
options	KDB\n\
options	DDB\n\
options	ALT_BREAK_TO_DEBUGGER\n\
options	CFE_CONSOLE\n\
options	CFE\n\
options	CPU_SENTRY5\n\
options	ISA_MIPS32\n\
options	GEOM_PART_MBR\n\
options	GEOM_PART_BSD\n\
device	mem\n\
device	uart_ns8250\n\
device	siba\n\
device	pci\n\
device	usb\n\
device	uhci\n\
device	ehci\n\
device	loop\n\
device	ether\n\
device	md\n\
";

#endif /* INCLUDE_CONFIG_FILE */
